package ru.bulatov.liferay.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import ru.bulatov.liferay.model.banks;
import ru.bulatov.liferay.service.banksLocalServiceUtil;

/**
 * The extended model base implementation for the banks service. Represents a row in the &quot;liferay_banks&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link banksImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see banksImpl
 * @see ru.bulatov.liferay.model.banks
 * @generated
 */
public abstract class banksBaseImpl extends banksModelImpl implements banks {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a banks model instance should use the {@link banks} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            banksLocalServiceUtil.addbanks(this);
        } else {
            banksLocalServiceUtil.updatebanks(this);
        }
    }
}
