package ru.bulatov.liferay.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import ru.bulatov.liferay.model.positions;
import ru.bulatov.liferay.service.positionsLocalServiceUtil;

/**
 * The extended model base implementation for the positions service. Represents a row in the &quot;liferay_positions&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link positionsImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see positionsImpl
 * @see ru.bulatov.liferay.model.positions
 * @generated
 */
public abstract class positionsBaseImpl extends positionsModelImpl
    implements positions {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a positions model instance should use the {@link positions} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            positionsLocalServiceUtil.addpositions(this);
        } else {
            positionsLocalServiceUtil.updatepositions(this);
        }
    }
}
