package ru.bulatov.liferay.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import ru.bulatov.liferay.model.positions;
import ru.bulatov.liferay.model.positionsModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the positions service. Represents a row in the &quot;liferay_positions&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link ru.bulatov.liferay.model.positionsModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link positionsImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see positionsImpl
 * @see ru.bulatov.liferay.model.positions
 * @see ru.bulatov.liferay.model.positionsModel
 * @generated
 */
public class positionsModelImpl extends BaseModelImpl<positions>
    implements positionsModel {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a positions model instance should use the {@link ru.bulatov.liferay.model.positions} interface instead.
     */
    public static final String TABLE_NAME = "liferay_positions";
    public static final Object[][] TABLE_COLUMNS = {
            { "position_id", Types.BIGINT },
            { "position_name", Types.VARCHAR },
            { "archive_status", Types.BOOLEAN }
        };
    public static final String TABLE_SQL_CREATE = "create table liferay_positions (position_id LONG not null primary key,position_name VARCHAR(75) null,archive_status BOOLEAN)";
    public static final String TABLE_SQL_DROP = "drop table liferay_positions";
    public static final String ORDER_BY_JPQL = " ORDER BY positions.position_id ASC";
    public static final String ORDER_BY_SQL = " ORDER BY liferay_positions.position_id ASC";
    public static final String DATA_SOURCE = "liferayDataSource";
    public static final String SESSION_FACTORY = "liferaySessionFactory";
    public static final String TX_MANAGER = "liferayTransactionManager";
    public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.entity.cache.enabled.ru.bulatov.liferay.model.positions"),
            true);
    public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.finder.cache.enabled.ru.bulatov.liferay.model.positions"),
            true);
    public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.column.bitmask.enabled.ru.bulatov.liferay.model.positions"),
            true);
    public static long ARCHIVE_STATUS_COLUMN_BITMASK = 1L;
    public static long POSITION_ID_COLUMN_BITMASK = 2L;
    public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
                "lock.expiration.time.ru.bulatov.liferay.model.positions"));
    private static ClassLoader _classLoader = positions.class.getClassLoader();
    private static Class<?>[] _escapedModelInterfaces = new Class[] {
            positions.class
        };
    private long _position_id;
    private String _position_name;
    private boolean _archive_status;
    private boolean _originalArchive_status;
    private boolean _setOriginalArchive_status;
    private long _columnBitmask;
    private positions _escapedModel;

    public positionsModelImpl() {
    }

    @Override
    public long getPrimaryKey() {
        return _position_id;
    }

    @Override
    public void setPrimaryKey(long primaryKey) {
        setPosition_id(primaryKey);
    }

    @Override
    public Serializable getPrimaryKeyObj() {
        return _position_id;
    }

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj) {
        setPrimaryKey(((Long) primaryKeyObj).longValue());
    }

    @Override
    public Class<?> getModelClass() {
        return positions.class;
    }

    @Override
    public String getModelClassName() {
        return positions.class.getName();
    }

    @Override
    public Map<String, Object> getModelAttributes() {
        Map<String, Object> attributes = new HashMap<String, Object>();

        attributes.put("position_id", getPosition_id());
        attributes.put("position_name", getPosition_name());
        attributes.put("archive_status", getArchive_status());

        return attributes;
    }

    @Override
    public void setModelAttributes(Map<String, Object> attributes) {
        Long position_id = (Long) attributes.get("position_id");

        if (position_id != null) {
            setPosition_id(position_id);
        }

        String position_name = (String) attributes.get("position_name");

        if (position_name != null) {
            setPosition_name(position_name);
        }

        Boolean archive_status = (Boolean) attributes.get("archive_status");

        if (archive_status != null) {
            setArchive_status(archive_status);
        }
    }

    @Override
    public long getPosition_id() {
        return _position_id;
    }

    @Override
    public void setPosition_id(long position_id) {
        _position_id = position_id;
    }

    @Override
    public String getPosition_name() {
        if (_position_name == null) {
            return StringPool.BLANK;
        } else {
            return _position_name;
        }
    }

    @Override
    public void setPosition_name(String position_name) {
        _position_name = position_name;
    }

    @Override
    public boolean getArchive_status() {
        return _archive_status;
    }

    @Override
    public boolean isArchive_status() {
        return _archive_status;
    }

    @Override
    public void setArchive_status(boolean archive_status) {
        _columnBitmask |= ARCHIVE_STATUS_COLUMN_BITMASK;

        if (!_setOriginalArchive_status) {
            _setOriginalArchive_status = true;

            _originalArchive_status = _archive_status;
        }

        _archive_status = archive_status;
    }

    public boolean getOriginalArchive_status() {
        return _originalArchive_status;
    }

    public long getColumnBitmask() {
        return _columnBitmask;
    }

    @Override
    public ExpandoBridge getExpandoBridge() {
        return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
            positions.class.getName(), getPrimaryKey());
    }

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
        ExpandoBridge expandoBridge = getExpandoBridge();

        expandoBridge.setAttributes(serviceContext);
    }

    @Override
    public positions toEscapedModel() {
        if (_escapedModel == null) {
            _escapedModel = (positions) ProxyUtil.newProxyInstance(_classLoader,
                    _escapedModelInterfaces, new AutoEscapeBeanHandler(this));
        }

        return _escapedModel;
    }

    @Override
    public Object clone() {
        positionsImpl positionsImpl = new positionsImpl();

        positionsImpl.setPosition_id(getPosition_id());
        positionsImpl.setPosition_name(getPosition_name());
        positionsImpl.setArchive_status(getArchive_status());

        positionsImpl.resetOriginalValues();

        return positionsImpl;
    }

    @Override
    public int compareTo(positions positions) {
        long primaryKey = positions.getPrimaryKey();

        if (getPrimaryKey() < primaryKey) {
            return -1;
        } else if (getPrimaryKey() > primaryKey) {
            return 1;
        } else {
            return 0;
        }
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }

        if (!(obj instanceof positions)) {
            return false;
        }

        positions positions = (positions) obj;

        long primaryKey = positions.getPrimaryKey();

        if (getPrimaryKey() == primaryKey) {
            return true;
        } else {
            return false;
        }
    }

    @Override
    public int hashCode() {
        return (int) getPrimaryKey();
    }

    @Override
    public void resetOriginalValues() {
        positionsModelImpl positionsModelImpl = this;

        positionsModelImpl._originalArchive_status = positionsModelImpl._archive_status;

        positionsModelImpl._setOriginalArchive_status = false;

        positionsModelImpl._columnBitmask = 0;
    }

    @Override
    public CacheModel<positions> toCacheModel() {
        positionsCacheModel positionsCacheModel = new positionsCacheModel();

        positionsCacheModel.position_id = getPosition_id();

        positionsCacheModel.position_name = getPosition_name();

        String position_name = positionsCacheModel.position_name;

        if ((position_name != null) && (position_name.length() == 0)) {
            positionsCacheModel.position_name = null;
        }

        positionsCacheModel.archive_status = getArchive_status();

        return positionsCacheModel;
    }

    @Override
    public String toString() {
        StringBundler sb = new StringBundler(7);

        sb.append("{position_id=");
        sb.append(getPosition_id());
        sb.append(", position_name=");
        sb.append(getPosition_name());
        sb.append(", archive_status=");
        sb.append(getArchive_status());
        sb.append("}");

        return sb.toString();
    }

    @Override
    public String toXmlString() {
        StringBundler sb = new StringBundler(13);

        sb.append("<model><model-name>");
        sb.append("ru.bulatov.liferay.model.positions");
        sb.append("</model-name>");

        sb.append(
            "<column><column-name>position_id</column-name><column-value><![CDATA[");
        sb.append(getPosition_id());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>position_name</column-name><column-value><![CDATA[");
        sb.append(getPosition_name());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>archive_status</column-name><column-value><![CDATA[");
        sb.append(getArchive_status());
        sb.append("]]></column-value></column>");

        sb.append("</model>");

        return sb.toString();
    }
}
