package ru.bulatov.liferay.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the banks service. Represents a row in the &quot;liferay_banks&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link ru.bulatov.liferay.model.impl.banksModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ru.bulatov.liferay.model.impl.banksImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see banks
 * @see ru.bulatov.liferay.model.impl.banksImpl
 * @see ru.bulatov.liferay.model.impl.banksModelImpl
 * @generated
 */
public interface banksModel extends BaseModel<banks> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a banks model instance should use the {@link banks} interface instead.
     */

    /**
     * Returns the primary key of this banks.
     *
     * @return the primary key of this banks
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this banks.
     *
     * @param primaryKey the primary key of this banks
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the bank_id of this banks.
     *
     * @return the bank_id of this banks
     */
    public long getBank_id();

    /**
     * Sets the bank_id of this banks.
     *
     * @param bank_id the bank_id of this banks
     */
    public void setBank_id(long bank_id);

    /**
     * Returns the bank_name of this banks.
     *
     * @return the bank_name of this banks
     */
    @AutoEscape
    public String getBank_name();

    /**
     * Sets the bank_name of this banks.
     *
     * @param bank_name the bank_name of this banks
     */
    public void setBank_name(String bank_name);

    /**
     * Returns the bik of this banks.
     *
     * @return the bik of this banks
     */
    @AutoEscape
    public String getBik();

    /**
     * Sets the bik of this banks.
     *
     * @param bik the bik of this banks
     */
    public void setBik(String bik);

    /**
     * Returns the bank_address of this banks.
     *
     * @return the bank_address of this banks
     */
    @AutoEscape
    public String getBank_address();

    /**
     * Sets the bank_address of this banks.
     *
     * @param bank_address the bank_address of this banks
     */
    public void setBank_address(String bank_address);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(ru.bulatov.liferay.model.banks banks);

    @Override
    public int hashCode();

    @Override
    public CacheModel<ru.bulatov.liferay.model.banks> toCacheModel();

    @Override
    public ru.bulatov.liferay.model.banks toEscapedModel();

    @Override
    public ru.bulatov.liferay.model.banks toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
