package ru.bulatov.liferay.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the employees service. Represents a row in the &quot;liferay_employees&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link ru.bulatov.liferay.model.impl.employeesModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ru.bulatov.liferay.model.impl.employeesImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see employees
 * @see ru.bulatov.liferay.model.impl.employeesImpl
 * @see ru.bulatov.liferay.model.impl.employeesModelImpl
 * @generated
 */
public interface employeesModel extends BaseModel<employees> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a employees model instance should use the {@link employees} interface instead.
     */

    /**
     * Returns the primary key of this employees.
     *
     * @return the primary key of this employees
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this employees.
     *
     * @param primaryKey the primary key of this employees
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the employee_id of this employees.
     *
     * @return the employee_id of this employees
     */
    public long getEmployee_id();

    /**
     * Sets the employee_id of this employees.
     *
     * @param employee_id the employee_id of this employees
     */
    public void setEmployee_id(long employee_id);

    /**
     * Returns the lastname of this employees.
     *
     * @return the lastname of this employees
     */
    @AutoEscape
    public String getLastname();

    /**
     * Sets the lastname of this employees.
     *
     * @param lastname the lastname of this employees
     */
    public void setLastname(String lastname);

    /**
     * Returns the firstname of this employees.
     *
     * @return the firstname of this employees
     */
    @AutoEscape
    public String getFirstname();

    /**
     * Sets the firstname of this employees.
     *
     * @param firstname the firstname of this employees
     */
    public void setFirstname(String firstname);

    /**
     * Returns the middlename of this employees.
     *
     * @return the middlename of this employees
     */
    @AutoEscape
    public String getMiddlename();

    /**
     * Sets the middlename of this employees.
     *
     * @param middlename the middlename of this employees
     */
    public void setMiddlename(String middlename);

    /**
     * Returns the gender of this employees.
     *
     * @return the gender of this employees
     */
    @AutoEscape
    public String getGender();

    /**
     * Sets the gender of this employees.
     *
     * @param gender the gender of this employees
     */
    public void setGender(String gender);

    /**
     * Returns the date_of_birth of this employees.
     *
     * @return the date_of_birth of this employees
     */
    @AutoEscape
    public String getDate_of_birth();

    /**
     * Sets the date_of_birth of this employees.
     *
     * @param date_of_birth the date_of_birth of this employees
     */
    public void setDate_of_birth(String date_of_birth);

    /**
     * Returns the date_of_employment of this employees.
     *
     * @return the date_of_employment of this employees
     */
    @AutoEscape
    public String getDate_of_employment();

    /**
     * Sets the date_of_employment of this employees.
     *
     * @param date_of_employment the date_of_employment of this employees
     */
    public void setDate_of_employment(String date_of_employment);

    /**
     * Returns the position_id of this employees.
     *
     * @return the position_id of this employees
     */
    public long getPosition_id();

    /**
     * Sets the position_id of this employees.
     *
     * @param position_id the position_id of this employees
     */
    public void setPosition_id(long position_id);

    /**
     * Returns the salary of this employees.
     *
     * @return the salary of this employees
     */
    public long getSalary();

    /**
     * Sets the salary of this employees.
     *
     * @param salary the salary of this employees
     */
    public void setSalary(long salary);

    /**
     * Returns the work_phonenumber of this employees.
     *
     * @return the work_phonenumber of this employees
     */
    @AutoEscape
    public String getWork_phonenumber();

    /**
     * Sets the work_phonenumber of this employees.
     *
     * @param work_phonenumber the work_phonenumber of this employees
     */
    public void setWork_phonenumber(String work_phonenumber);

    /**
     * Returns the mobile_phonenumber of this employees.
     *
     * @return the mobile_phonenumber of this employees
     */
    @AutoEscape
    public String getMobile_phonenumber();

    /**
     * Sets the mobile_phonenumber of this employees.
     *
     * @param mobile_phonenumber the mobile_phonenumber of this employees
     */
    public void setMobile_phonenumber(String mobile_phonenumber);

    /**
     * Returns the bank_id of this employees.
     *
     * @return the bank_id of this employees
     */
    public long getBank_id();

    /**
     * Sets the bank_id of this employees.
     *
     * @param bank_id the bank_id of this employees
     */
    public void setBank_id(long bank_id);

    /**
     * Returns the archive_status of this employees.
     *
     * @return the archive_status of this employees
     */
    public boolean getArchive_status();

    /**
     * Returns <code>true</code> if this employees is archive_status.
     *
     * @return <code>true</code> if this employees is archive_status; <code>false</code> otherwise
     */
    public boolean isArchive_status();

    /**
     * Sets whether this employees is archive_status.
     *
     * @param archive_status the archive_status of this employees
     */
    public void setArchive_status(boolean archive_status);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(ru.bulatov.liferay.model.employees employees);

    @Override
    public int hashCode();

    @Override
    public CacheModel<ru.bulatov.liferay.model.employees> toCacheModel();

    @Override
    public ru.bulatov.liferay.model.employees toEscapedModel();

    @Override
    public ru.bulatov.liferay.model.employees toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
