package ru.bulatov.liferay.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the positions service. Represents a row in the &quot;liferay_positions&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link ru.bulatov.liferay.model.impl.positionsModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ru.bulatov.liferay.model.impl.positionsImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see positions
 * @see ru.bulatov.liferay.model.impl.positionsImpl
 * @see ru.bulatov.liferay.model.impl.positionsModelImpl
 * @generated
 */
public interface positionsModel extends BaseModel<positions> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a positions model instance should use the {@link positions} interface instead.
     */

    /**
     * Returns the primary key of this positions.
     *
     * @return the primary key of this positions
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this positions.
     *
     * @param primaryKey the primary key of this positions
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the position_id of this positions.
     *
     * @return the position_id of this positions
     */
    public long getPosition_id();

    /**
     * Sets the position_id of this positions.
     *
     * @param position_id the position_id of this positions
     */
    public void setPosition_id(long position_id);

    /**
     * Returns the position_name of this positions.
     *
     * @return the position_name of this positions
     */
    @AutoEscape
    public String getPosition_name();

    /**
     * Sets the position_name of this positions.
     *
     * @param position_name the position_name of this positions
     */
    public void setPosition_name(String position_name);

    /**
     * Returns the archive_status of this positions.
     *
     * @return the archive_status of this positions
     */
    public boolean getArchive_status();

    /**
     * Returns <code>true</code> if this positions is archive_status.
     *
     * @return <code>true</code> if this positions is archive_status; <code>false</code> otherwise
     */
    public boolean isArchive_status();

    /**
     * Sets whether this positions is archive_status.
     *
     * @param archive_status the archive_status of this positions
     */
    public void setArchive_status(boolean archive_status);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(ru.bulatov.liferay.model.positions positions);

    @Override
    public int hashCode();

    @Override
    public CacheModel<ru.bulatov.liferay.model.positions> toCacheModel();

    @Override
    public ru.bulatov.liferay.model.positions toEscapedModel();

    @Override
    public ru.bulatov.liferay.model.positions toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
